--- 
after_succes: 
  - coveralls
before_script: 
  - "pip install docker-compose"
  - "pip install coveralls"
deploy: 
  provider: script
  script: "bash ci/travis-deploy.sh"
  skip-cleanup: true
  true: 
    branch: master
language: python
python: 
  - "3.8"
script: 
  - "docker-compose run app sh -c \"pytest test.py\""
services: 
  - docker
sudo: true
