version: "3.8"
services:
    app:
        build: .
        command: sh -c "python main.py"
        # Replace "YOUR_USER" for your Docker Hub user
        # docker hub is a repository of docker images
        image: xuei/cicd-example2:latest
        ports:
            - "80:8000"